---
- name: Download opnsense example.config from official repo
  get_url:
    url: https://raw.githubusercontent.com/opnsense/core/stable/22.1/src/etc/config.xml.sample
    dest:  "{{ packer_local_config_path }}"
    mode: '0660'
    owner: ansible
  when: packer

- name: fetch
  delegate_to: localhost
  fetch:
    src: "{{ config_path_packer }}"
    dest: "{{ local_config_path }}"
    flat: yes
    backup: yes
  when: reset
...