---
- name: Manage SSH Root Login
  lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: "PermitRootLogin {{ permit_root }}"
        state: present
        backup: yes
  become: yes
  notify:
    - restart ssh