---
- hosts: opnsense
  gather_facts: false
  become: false

  vars_files:
    - "{{ inventory_dir}}/vars/opnsense_openvpn.yml"

  vars:
    ansible_python_interpreter: "/opt/venv/bin/python3"

  roles:
    - ansible-opnsense